name: production_on_push

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 18.x
  production:
    concurrency:
      cancel-in-progress: true
    with:
      checks: "['npm:lint']"
      
